apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nashussadb
  name: nashussadb
  namespace: nashussa-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nashussadb
  strategy: {}
  template:  # pod template
    metadata:
      creationTimestamp: null
      labels:
        app: nashussadb
    spec:
      volumes: # to create volume
      - name: nashussadbvol
        hostPath: # pod will take space from Minion node
         path: /data/nashussadb
         type: DirectoryOrCreate
      containers:
      - image: mysql:5.7
        name: mysql
        ports:
        - containerPort: 3306
        envFrom: # to call env variable from configMAP
        - configMapRef:
           name: db-config # name of configMAP
        env: # calling other env with secret
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_pass
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nashussadb-sec
              key: root_pass
        resources: {}
        volumeMounts: # to mount the volume created above
        - name: nashussadbvol
          mountPath: /var/lib/mysql/
status: {}
