apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nashussawebapp
  name: nashussawebapp
  namespace: nashussa-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nashussawebapp
  strategy: {}
  template: # pod info 
    metadata:
      creationTimestamp: null
      labels: # label of pods
        app: nashussawebapp
    spec:
      containers:
      - image: wordpress
        name: wordpress
        ports:
        - containerPort: 80
        envFrom: # calling docker image env variables 
        - configMapRef:
           name: nashussaweb-config 
        env: # to call password from secret 
        - name: WORDPRESS_DB_PASSWORD
          valueFrom: # taking data from secret 
           secretKeyRef:
            name: nashussadb-sec
            key: db_pass 

        resources: {}
status: {}
